INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION,PRICE) VALUES ('Note Acer', '16gb RAM', 4000);
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION,PRICE) VALUES ('Xbox One', '1 TB', 2500);
INSERT INTO TBL_PRODUCT (NAME, DESCRIPTION,PRICE) VALUES ('Galaxy A20', '8gb RAM', 2000);